# Generated by Django 4.0.4 on 2022-06-19 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_gender_delete_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username should not included with space', regex='^\\S*$')]),
        ),
    ]
