# Generated by Django 4.0.4 on 2022-07-10 14:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to=users.models.upload_to, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
